### ISSUE TITLE
create box default bonus token is now main token, which will cause a revert 

### ISSUE THREAD

**Issue by antoncoding** [hodlmybeer/frontend#11]

**Comment by alxkzmn** [comment]
Do you mean to display a warning when the same token is selected?

**Comment by antoncoding** [comment]
yes add just default the bonus token to index -1 (and set to address 0)

**Comment by antoncoding** [comment]
I'm fixing this now

**Comment by alxkzmn** [comment]
I think the cleaner solution is to dynamically remove the main token from the bonus drop-down. Instead, you could display "None" option.
